server:
  port: 9316

spring:
  application:
    name: nsf-demo-stock-grpc-consumer
  sleuth:
    sampler:
      probability: 1

grpc:
  server:
    port: 9317
  client:
    nsf-demo-stock-grpc-provider:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext