grpc:
  client:
    nsf-demo-stock-grpc-provider:
      enableKeepAlive: false
      keepAliveWithoutCalls: false
      negotiationType: plaintext
      defaultLoadBalancingPolicy: round_robin
    nsf-demo-stock-grpc-entry:
      enableKeepAlive: false
      keepAliveWithoutCalls: false
      negotiationType: plaintext